version: '3'

services:
    php:
        container_name: ${DOCKER_PROJECT_NAME}_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        build: ./docker/php
